-- Generated by PZ Mod Studio
require "Items/ProceduralDistributions"

-- Distribution: BathroomCabinet
if ProceduralDistributions.list["BathroomCabinet"] then
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "DentalPain.DentalFloss");
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 2);
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "DentalPain.Mouthwash");
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 2);
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "DentalPain.HomemadeToothbrush");
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 0.5);
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, "DentalPain.HomemadeToothpaste");
    table.insert(ProceduralDistributions.list["BathroomCabinet"].items, 0.5);
end

-- Distribution: MedicalClinic
if ProceduralDistributions.list["MedicalClinic"] then
    table.insert(ProceduralDistributions.list["MedicalClinic"].items, "DentalPain.DentalAnesthetic");
    table.insert(ProceduralDistributions.list["MedicalClinic"].items, 1);
    table.insert(ProceduralDistributions.list["MedicalClinic"].items, "DentalPain.Mouthwash");
    table.insert(ProceduralDistributions.list["MedicalClinic"].items, 1);
end

